spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    url: jdbc:mysql://localhost:3306/springmvc_01_sampleapp?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: 'true'    